name: Contracts Workflow

on:
  schedule:
    - cron: "10 0 * * *" # Runs every day
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 200

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Environment Variables
        run: |
          echo "Checking CONTRACTING_GCLOUD_KEY_JSON..."
          echo $CONTRACTING_GCLOUD_KEY_JSON | head -c 50

      - name: Run the scraper
        env:
          CONTRACTING_GCLOUD_KEY_JSON: ${{ secrets.CONTRACTING_GCLOUD_KEY_JSON }}
        run: |
          python contracting_code_main.py

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: scraper-logs
          path: scraper.log
